### ISSUE TITLE
2.0.0 - notice when no homepage components are installed

### ISSUE THREAD

**Issue by danjjohnson** [woothemes/homepage-control#14]
If you activate the Homepage Control plugin when you don't have any related plugins activated, the section in the customiser is blank - http://cld.wthms.co/xHRg

Might be useful to add a message there explaining that you need the other plugins, maybe a link to the docs.

**Comment by tiagonoronha** [comment]
@danjjohnson suggestions for the message? :)

**Comment by danjjohnson** [comment]
"No homepage components found. See the docs (link) for details of available homepage component plugins/themes."

We'll probably need to update the docs too, as they don't mention that you can use it with plugins http://docs.woothemes.com/document/homepage-control/
