### ISSUE TITLE
Tag for 2.0.0 release?

### ISSUE THREAD

**Issue by tidalvirus** [woothemes/homepage-control#16]
Hi,

I was wondering if you could add a tag in for the 2.0.0 release as released? I assume it would be this commit https://github.com/woothemes/homepage-control/commit/7ac960e744e48a858d32e0c03020900551df308d ?

I'd submit a pull request, but I'm not sure how to for this at this stage. :)

Thanks!

Sid

**Comment by tiagonoronha** [comment]
Hi @tidalvirus, I tagged 2.0.0 - https://github.com/woothemes/homepage-control/releases/tag/version%2F2.0.0

Feel free to submit a pull request directly to master. :)

Thanks
