### ISSUE TITLE
Renaming default woo_ prefixes causes inconsistent behavior

### ISSUE THREAD

**Issue by johnbuck** [woothemes/homepage-control#7]
Hey guys,

I'm writing a plugin to extend Canvas with a few more options and allow an easily customizable one page homepage. I'm using the integrations code from Stitched as a base, and renamed the woo_prefixes to avoid any conflicts with already declared functions.

Unfortunately this causes issues with the homepage control. The renamed function is recognized as a newly hooked function, but homepage control doesn't recognize that the old function no longer exists.

http://d.pr/i/Bgbo

And because homepage control is still looking for that function, it creates errors on the frontend.

http://d.pr/i/qj0L

Just thought you should know. :)

**Comment by tiagonoronha** [comment]
@johnbuck I'm closing this issue. @jameskoster suggestion is the way to go on this specific case. :)

Thanks.
